CREATE DATABASE IF NOT EXISTS RETAIL;

CREATE TABLE IF NOT EXISTS RETAIL.ADDRESS (
	ADDRESS_ID INT AUTO_INCREMENT,
	CITY VARCHAR(20),
	DISTRICT VARCHAR(20),
	SUB_DISTRICT VARCHAR(20),
	POSTAL_CODE VARCHAR(20),
	DELIVERY_FEE INT,

	CONSTRAINT PK_ADDRESS PRIMARY KEY (ADDRESS_ID)
);

CREATE TABLE IF NOT EXISTS RETAIL.CUSTOMER (
	CUSTOMER_ID INT AUTO_INCREMENT,
	FULL_NAME VARCHAR(50),
	EMAIL VARCHAR(50),
	PHONE_NUMBER VARCHAR(10),
	ADDRESS_ID INT,

	CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID),
	CONSTRAINT FK_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES RETAIL.ADDRESS(ADDRESS_ID)
);

CREATE TABLE IF NOT EXISTS RETAIL.DISCOUNT (
	DISCOUNT_ID INT AUTO_INCREMENT,
	TITLE VARCHAR(50),
	TYPE VARCHAR(50),
	DISCOUNT INT,
	START_DATE DATE,
	END_DATE DATE,
	
	CONSTRAINT PK_DISCOUNT PRIMARY KEY (DISCOUNT_ID)
);

CREATE TABLE IF NOT EXISTS RETAIL.PRODUCT (
	PRODUCT_ID INT AUTO_INCREMENT,
	NAME VARCHAR(100),
	DESCRIPTION VARCHAR(255),
	PRICE INT,
	DISCOUTN_PRICE INT,
	STOCK INT,
	SOLD INT,
	CREATE_DATE DATE,
	STATUS VARCHAR(50),

	CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS RETAIL.ORDER (
	ORDER_ID INT AUTO_INCREMENT,
	NAME VARCHAR(20),
	PHONE_NUMBER VARCHAR(10),
	DETAIL_ADDRESS VARCHAR(50),
	TOTAL INT,
	ORDER_DATE DATE,
	CUSTOMER_ID INT,
	ADDRESS_ID INT,
	DISCOUNT_ID INT,

	CONSTRAINT PK_ORDER PRIMARY KEY (ORDER_ID),
	CONSTRAINT FK_DISCOUNT FOREIGN KEY (DISCOUNT_ID) REFERENCES RETAIL.DISCOUNT(DISCOUNT_ID),
	CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES RETAIL.CUSTOMER(CUSTOMER_ID),
	CONSTRAINT FK_ADDRESS1 FOREIGN KEY (ADDRESS_ID) REFERENCES RETAIL.ADDRESS(ADDRESS_ID)
);

CREATE TABLE IF NOT EXISTS RETAIL.ORDER_DETAIL (
	CART_ID INT AUTO_INCREMENT,
	QUANTITY INT,
	TOTAL INT,
	ORDER_ID INT,
	PRODUCT_ID INT,

	CONSTRAINT PK_ORDER_DETAIL PRIMARY KEY (CART_ID),
	CONSTRAINT FK_ORDER FOREIGN KEY (ORDER_ID) REFERENCES RETAIL.ORDER(ORDER_ID),
	CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES RETAIL.PRODUCT(PRODUCT_ID)
);
